### ISSUE TITLE
Get error if label is not present

### ISSUE THREAD

**Issue by mountwebs** [MaciejGL/final-project-frontend#20]
The input component gives this error if the input does not have a label:

"A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component."

**Comment by mountwebs** [comment]
My mistake, sorry! 😅

**Comment by MaciejGL** [comment]
I Guess its solved 👍
